image: docker:latest

services:
  - docker:dind

stages:
  - build_test

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build_test:
  stage: build_test
  script:
    # Build the Docker image using the root Dockerfile
    - docker build --build-arg GIT_TOKEN=${GIT_TOKEN} -t lgustavolp/robotframework .

    # Run the built Docker image and run the tests
    - docker run --rm -v ${PWD}/tests:/tests -v ${PWD}/resources:/resources -v ${PWD}/results:/results --entrypoint robot lgustavolp/robotframework --outputdir /results /tests/player.robot
  artifacts:
    paths:
      - results
    expire_in: 1 week
