image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build_image:
  stage: build
  script:
    # Construir a imagem Docker usando o Dockerfile da raiz
    - docker build -t lgustavolp/robotframework .

test_robot:
  stage: test
  script:
    # Executar a imagem Docker construída e rodar os testes
    - docker run --rm -v ${PWD}/tests:/tests -v ${PWD}/resources:/resources \
    -v ${PWD}/results:/results --entrypoint robot lgustavolp/robotframework \
    --outputdir /results /tests/player.robot
  artifacts:
    paths:
      - results
    expire_in: 1 week
